/* global __dirname */
// Turns game/game.html into a JS module so the app can hand it to the WebView
// without any asset loading (works the same in Expo Go on iOS and Android).
const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '..', 'game', 'game.html');
const out = path.join(__dirname, '..', 'game', 'gameHtml.js');

const html = fs.readFileSync(src, 'utf8');
fs.writeFileSync(
  out,
  '// Generated by scripts/build-game.js from game/game.html. Do not edit by hand.\n' +
    `export default ${JSON.stringify(html)};\n`
);
console.log(`game/gameHtml.js written (${(html.length / 1024).toFixed(1)} KB)`);
